# Generated by Django 4.0 on 2021-12-09 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledWebPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Only domain name', max_length=250, unique=True)),
                ('sitemap_filepath', models.SlugField(blank=True, help_text='The sitemap.xml file path', max_length=250, null=True)),
                ('robot_txt_filepath', models.SlugField(blank=True, help_text='The robot.txt file path', max_length=250, null=True)),
                ('uses', models.PositiveBigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('http_status', models.IntegerField(choices=[(100, 'Continue'), (101, 'Switching protocols'), (102, 'Processing'), (103, 'Early Hints'), (200, 'Ok'), (201, 'Created'), (202, 'Accepted'), (203, 'Non-Authoritative Information'), (204, 'No Content'), (205, 'Reset Content'), (206, 'Partial Content'), (207, 'Multi-Status'), (208, 'Already Reported'), (226, 'IM Used'), (300, 'Multiple Choices'), (301, 'Moved Permanently'), (302, 'Found (Previously "Moved Temporarily")'), (303, 'See Other'), (304, 'Not Modified'), (305, 'Use Proxy'), (306, 'Switch Proxy'), (307, 'Temporary Redirect'), (308, 'Permanent Redirect'), (400, 'Bad Request'), (401, 'Unauthorized'), (402, 'Payment Required'), (403, 'Forbidden'), (404, 'Not Found'), (405, 'Method Not Allowed'), (406, 'Not Acceptable'), (407, 'Proxy Authentication Required'), (408, 'Request Timeout'), (409, 'Conflict'), (410, 'Gone'), (411, 'Length Required'), (412, 'Precondition Failed'), (413, 'Payload Too Large'), (414, 'URI Too Long'), (415, 'Unsupported Media Type'), (416, 'Range Not Satisfiable'), (417, 'Expectation Failed'), (418, "I'm a Teapot"), (421, 'Misdirected Request'), (422, 'Unprocessable Entity'), (423, 'Locked'), (424, 'Failed Dependency'), (425, 'Too Early'), (426, 'Upgrade Required'), (428, 'Precondition Required'), (429, 'Too Many Requests'), (431, 'Request Header Fields Too Large'), (451, 'Unavailable For Legal Reasons'), (500, 'Internal Server Error'), (501, 'Not Implemented'), (502, 'Bad Gateway'), (503, 'Service Unavailable'), (504, 'Gateway Timeout'), (505, 'HTTP Version Not Supported'), (506, 'Variant Also Negotiates'), (507, 'Insufficient Storage'), (508, 'Loop Detected'), (510, 'Not Extended'), (511, 'Network Authentication Required')], default=200)),
                ('scan_internal_links', models.BooleanField(default=True)),
                ('keywords_meta_tags', models.TextField(blank=True, null=True)),
                ('keywords_in_site', models.TextField(blank=True, null=True)),
                ('stripped_request_body', models.TextField(blank=True, help_text='Mainly the description to display', null=True)),
                ('keywords_ranking', models.JSONField(blank=True, default=dict, null=True)),
                ('last_crawled', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Crawled Web Pages',
                'ordering': ('uses',),
            },
        ),
        migrations.CreateModel(
            name='ToBeCrawledWebPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Only domain name', max_length=250, unique=True)),
                ('scan_internal_links', models.BooleanField(default=True)),
                ('http_status', models.IntegerField(choices=[(100, 'Continue'), (101, 'Switching protocols'), (102, 'Processing'), (103, 'Early Hints'), (200, 'Ok'), (201, 'Created'), (202, 'Accepted'), (203, 'Non-Authoritative Information'), (204, 'No Content'), (205, 'Reset Content'), (206, 'Partial Content'), (207, 'Multi-Status'), (208, 'Already Reported'), (226, 'IM Used'), (300, 'Multiple Choices'), (301, 'Moved Permanently'), (302, 'Found (Previously "Moved Temporarily")'), (303, 'See Other'), (304, 'Not Modified'), (305, 'Use Proxy'), (306, 'Switch Proxy'), (307, 'Temporary Redirect'), (308, 'Permanent Redirect'), (400, 'Bad Request'), (401, 'Unauthorized'), (402, 'Payment Required'), (403, 'Forbidden'), (404, 'Not Found'), (405, 'Method Not Allowed'), (406, 'Not Acceptable'), (407, 'Proxy Authentication Required'), (408, 'Request Timeout'), (409, 'Conflict'), (410, 'Gone'), (411, 'Length Required'), (412, 'Precondition Failed'), (413, 'Payload Too Large'), (414, 'URI Too Long'), (415, 'Unsupported Media Type'), (416, 'Range Not Satisfiable'), (417, 'Expectation Failed'), (418, "I'm a Teapot"), (421, 'Misdirected Request'), (422, 'Unprocessable Entity'), (423, 'Locked'), (424, 'Failed Dependency'), (425, 'Too Early'), (426, 'Upgrade Required'), (428, 'Precondition Required'), (429, 'Too Many Requests'), (431, 'Request Header Fields Too Large'), (451, 'Unavailable For Legal Reasons'), (500, 'Internal Server Error'), (501, 'Not Implemented'), (502, 'Bad Gateway'), (503, 'Service Unavailable'), (504, 'Gateway Timeout'), (505, 'HTTP Version Not Supported'), (506, 'Variant Also Negotiates'), (507, 'Insufficient Storage'), (508, 'Loop Detected'), (510, 'Not Extended'), (511, 'Network Authentication Required')], default=200)),
                ('last_crawled', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'To Be Crawled Web Pages',
                'ordering': ('last_crawled',),
            },
        ),
        migrations.AddIndex(
            model_name='tobecrawledwebpages',
            index=models.Index(fields=['url', 'http_status'], include=('last_crawled',), name='url_and_http_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tobecrawledwebpages',
            index=models.Index(fields=['url'], include=('last_crawled',), name='url_tobecrawled_idx'),
        ),
        migrations.AddIndex(
            model_name='tobecrawledwebpages',
            index=models.Index(fields=['http_status'], include=('last_crawled',), name='http_status_idx'),
        ),
        migrations.AddIndex(
            model_name='crawledwebpages',
            index=models.Index(fields=['url'], include=('uses',), name='url_idx'),
        ),
    ]
