# Generated by Django 4.0 on 2021-12-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crawledwebpages',
            name='url_and_ip_address_idx',
        ),
        migrations.RemoveIndex(
            model_name='crawledwebpages',
            name='ip_address_idx',
        ),
    ]
