# Generated by Django 4.0 on 2021-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_crawledwebpages_url_and_ip_address_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crawledwebpages',
            name='url_idx',
        ),
        migrations.AddIndex(
            model_name='crawledwebpages',
            index=models.Index(fields=['url'], include=('uses',), name='url_idx'),
        ),
    ]
